### ISSUE TITLE
Jumpy window when programmatically resizing. [Linux]

### ISSUE THREAD

**Issue by Fordi** [mcchatman8009/native-canvas#2]
Sample code demonstrating break:

```javascript
require('native-canvas');
canvas.width = 800;
canvas.height = 450;
```

When running that code, the window jitters between the default size (640x480) and the requested size (800x450).  I've tried a number of combinations against exposed properties (e.g., `window.size = { w: 800, h: 450 }`, etc).  Nothing appears to work.  Some things do nothing, others jitter madly.  I don't really know enough about SDL to dig in here, else, this'd be a pull request.

For context, I'm on Linux Mint 19 Cinnamon (like Ubuntu).  This doesn't happen in OS-X, and I don't have a windows machine to test with, so I don't know if the issue exists there.  It also happens in Raspbian (see PR #3  to test if you've got a Pi).

**Comment by mcchatman8009** [comment]
@Fordi Good find, I wonder if that is due to hardware acceleration option that is enabled. I'll try to look into this to see if I can reproduce this behavior. 

Thanks,
